module.exports = [
{"$id":0,
"nAME":"Argentinosaurus",
"fACT":"Biggest Herbivorous Dinosaur",
"tRIVIA":"Named after Argentina, where its remains were discovered in 1986. Argentinosaurus measured about 120 feet from head to tail and may have weighed nearly 100 tons. Just one of the vertebra of Argentinosaurus is over four feet thick.",
"image":{"url": "images/Argentinosaurus.jpg"},
"period": "Late Cretaceous Period",
"genus":"lognkosaurian titanosaur sauropod dinosaur",
"species": "Argentinosaurus huinculensis",
"height":"30–35 meters (98–115 ft)",
"weight":"60–88 tonnes (66–97 short tons)",
"location":"South America"
},

{"$id":1,
"nAME":"Spinosaurus",
"fACT":"Biggest Carnivorous Dinosaur",
"tRIVIA":"Weighing in as high as 10 tons. Not only was Spinosaurus big, but it was agile as well: recent evidence points to it being the world's first identified swimming dinosaur.",
"image":{"url": "images/Spinosaurus.jpg"},
"period": "Cretaceous period",
"genus":"theropod dinosaur",
"species": "Spinosaurus aegyptiacus",
"height":"15 meters (49 ft)",
"weight":"6 t (5.9 long tons; 6.6 short tons)",
"location":"North Africa"
},

{"$id":2,
"nAME":"Utahraptor",
"fACT":"Biggest Raptor",
"tRIVIA":"Weighed in at a whopping 1,500 pounds and was a full 20 feet long. The gigantic, curving hind claws of Utahraptor measured nearly a full foot long.",
"image":{"url": "images/Utahraptor.png"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":3,
"nAME":"Tyrannosaurus Rex",
"fACT":"Biggest Tyrannosaur",
"tRIVIA":"Weighed over 8 Tons. There's evidence that T. Rex females outweighed males by a half ton or so.",
"image":{"url": "images/Tyrannosaurus-rex.png"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":4,
"nAME":"Titanoceratops",
"fACT":"Biggest Horned, Frilled Dinosaur",
"tRIVIA":"Full-grown individuals measured 25 feet from head to tail and weighed over five tons.",
"image":{"url": "images/Titanoceratops.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":5,
"nAME":"Magnapaulia",
"fACT":"Biggest Duck-Billed Dinosaur",
"tRIVIA":"50-foot-long and 25-ton. Magnapaulia may have been capable of running on its two hind legs when pursued by predators",
"image":{"url": "images/Magnapaulia.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":6,
"nAME":"Gigantoraptor",
"fACT":"Biggest Dino-Bird",
"tRIVIA":"Weighing 2 Tons. We don't yet know whether Gigantoraptor preferred to eat meat or vegetables.",
"image":{"url": "images/Gigantoraptor.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":7,
"nAME":"Deinocheirus",
"fACT":"Biggest Bird Mimic Dinosaur",
"tRIVIA":"The six-ton Deinocheirus was a confirmed vegetarian, wielding its massive, clawed front hands like a pair of Cretaceous scythes.",
"image":{"url": "images/Deinocheirus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":8,
"nAME":"Riojasaurus",
"fACT":"Biggest Prosauropod",
"tRIVIA":"30-foot-long, 10-ton plant-eater of the late Triassic period. You can detect the proto-sauropod bona fides of Riojasaurus in its relatively long neck and tail, though its legs were much more slender than those of its massive descendants",
"image":{"url": "images/Riojasaurus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":9,
"nAME":"Quetzalcoatlus",
"fACT":"Biggest Pterosaur",
"tRIVIA":"35-Foot Wingspan and 500 lbs. This winged reptile was named after Quetzalcoatl, the feathered serpent god of the long-extinct Aztecs.",
"image":{"url": "images/Quetzalcoatlus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":10,
"nAME":"Sarcosuchus",
"fACT":"Biggest Crocodile",
"tRIVIA":"the 40-foot-long Sarcosuchus weighed as much as 15 tons--at least twice as long, and ten times as heavy, as the biggest crocodiles alive today.",
"image":{"url": "images/Sarcosuchus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":11,
"nAME":"Titanoboa",
"fACT":"Biggest Snake",
"tRIVIA":"The 50-foot-long, one-ton Titanoboa prowled the humid swamps of early Paleocene South America.",
"image":{"url": "images/Titanoboa.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":12,
"nAME":"Archelon",
"fACT":"Biggest Turtle",
"tRIVIA":"Archelon was a 12 feet long and weighed in the neighborhood of two tons, 4 times as much as the largest turtle today. The fossil remains of Archelon hail from Wyoming and South Dakota.",
"image":{"url": "images/Archelon.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":13,
"nAME":"Shastasaurus",
"fACT":"Biggest Ichthyosaur",
"tRIVIA":"The 75 ton Dolphin Like Creature Shastasaurus subsisted not on comparably sized fish and marine reptiles, but on soft-bodied cephalopods and other wee marine creatures",
"image":{"url": "images/Shastasaurus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":14,
"nAME":"Kronosaurus",
"fACT":"Biggest Pliosaur",
"tRIVIA":"This 7 ton pliosaur ruled the seas of the middle Cretaceous period, eating pretty much anything (fish, sharks, other marine reptiles) that happened across its path.",
"image":{"url": "images/Kronosaurus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":15,
"nAME":"Elasmosaurus",
"fACT":"Biggest Plesiosaur",
"tRIVIA":"This undersea predator measured about 45 feet from head to tail and weighed a two or three tons. It preyed smaller fish and squids.",
"image":{"url": "images/Elasmosaurus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":16,
"nAME":"Mosasaurus",
"fACT":"Biggest Mosasaur",
"tRIVIA":"At 50 feet long and 15 tons, Mosasaurus was the biggest, fiercest mosasaur of them all. In fact, the only creatures capable of competing with Mosasaurus and its ilk were slightly less enormous sharks.",
"image":{"url": "images/Mosasaurus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":17,
"nAME":"Smok",
"fACT":"Biggest Archosaur",
"tRIVIA":"Most archosaurs weighed only 10, 20, or perhaps 50 pounds, but the euphoniously named Smok was the exception that proved the rule: a dinosaur-like predator that tipped the scales at a full ton.",
"image":{"url": "images/Smok.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":18,
"nAME":"Moschops",
"fACT":"Biggest Therapsid",
"tRIVIA":"Moschops was the moo-cow of the late Permian period: this slow, ungainly, none-too-bright creature shuffled across the plains of southern Africa 255 million years ago, possibly in sizable herds.",
"image":{"url": "images/Moschops.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
},

{"$id":19,
"nAME":"Cotylorhynchus",
"fACT":"Biggest Pelycosaur",
"tRIVIA":"Cotylorhynchus weighed as much as two tons. Cotylorhynchus was a heavily built animal with a disproportionately small head and a huge barrel-shaped body",
"image":{"url": "images/Cotylorhynchus.jpg"},
"period": "",
"genus":"",
"species": "",
"height":"",
"weight":"",
"location":""
}
];